

export const data=[
    `1) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae viverra mauris, ac fermentum felis. Sed tempor ex a enim laoreet feugiat. Ut sit amet molestie nibh, sed scelerisque dolor. Integer lacinia tincidunt dolor ut ullamcorper. Nam gravida eu ante vitae tempor. Curabitur malesuada accumsan sapien, vel porta leo consequat et. Etiam lacus ligula, molestie nec orci ac, euismod convallis metus. Proin feugiat libero eu turpis ullamcorper cursus. Nunc ullamcorper pellentesque mauris sit amet semper. Aenean bibendum dapibus nulla in sodales. Etiam neque dolor, mollis eu volutpat quis, rhoncus vitae sem. Duis condimentum ipsum quis nisi tincidunt, ac auctor mauris eleifend.`,
    `2) In felis mi, elementum in congue ut, accumsan eget elit. Aenean id lorem lacinia, luctus nisi eu, finibus nunc. Nulla sollicitudin sodales sem, nec condimentum velit malesuada viverra. Fusce tincidunt neque eu augue efficitur ullamcorper. Maecenas dignissim sodales pretium. Praesent at sagittis ligula. Cras nec cursus purus. Nullam dictum, erat sed iaculis scelerisque, ante dui dignissim arcu, at blandit libero massa a velit. Donec tortor odio, elementum vitae fermentum vel, tempor eget dui. Vivamus eget euismod nisi. Nullam urna tortor, tristique sit amet sagittis vehicula, viverra ut tortor. Duis elit sem, aliquet ut dui eu, sodales interdum ex. Fusce ac tellus erat. Etiam aliquet dignissim sagittis.`,
    `3) Curabitur efficitur, massa at bibendum maximus, purus leo molestie nulla, pulvinar interdum mi nisl sed quam. Nunc egestas varius mattis. Nulla quis nisi pretium, euismod nisl ac, semper libero. Sed viverra sem nec fringilla varius. Vivamus lobortis mi ut mauris vulputate, sed blandit lacus finibus. In dignissim elementum quam, quis malesuada enim rutrum vel. Donec id leo quis velit elementum malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce sodales blandit nibh in aliquam. Ut ut ullamcorper lectus. In auctor suscipit elit. Phasellus lacinia ante sed magna dignissim facilisis. Mauris ac velit ut ex convallis tristique.`,
    `4) Aenean iaculis porta diam, eget imperdiet libero elementum in. Aenean dignissim nisl eu luctus ornare. Donec maximus metus leo, vitae vulputate diam dapibus vitae. Maecenas sagittis commodo ex sed viverra. Sed vitae lobortis nisl. Nam vestibulum euismod nulla. Cras euismod, orci eget pulvinar interdum, mauris tortor tempus enim, quis finibus ligula leo sed magna.`,
    `5) Quisque pharetra feugiat facilisis. Aenean sed ipsum ac nulla porta cursus quis at purus. Maecenas id odio vel risus tincidunt fringilla. Vestibulum velit quam, mollis eget finibus eu, vestibulum sit amet felis. Quisque vitae vestibulum magna. Nullam tempor varius leo nec fermentum. Nam eros nisl, porttitor quis iaculis eu, ornare sed libero.`,
    `6) Nunc quis sapien ut leo bibendum tincidunt vel id est. Vivamus et augue iaculis ante vestibulum vehicula ac quis ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec sit amet enim leo. Quisque luctus ligula vitae neque tempor pulvinar. Aliquam lobortis nunc in dignissim viverra. Cras pulvinar purus non mauris pulvinar, vitae accumsan felis accumsan. Duis nec venenatis arcu. Proin suscipit semper neque vel ullamcorper.`,
    `7) Pellentesque malesuada elit et enim sollicitudin, vel convallis quam condimentum. Integer condimentum elit eget elit eleifend vehicula. Mauris viverra ligula libero, ut hendrerit lectus tempor et. Sed congue massa ac erat hendrerit, eget auctor magna facilisis. Duis commodo eros id blandit vehicula. Etiam maximus condimentum dolor, eu malesuada risus. Etiam fermentum arcu dolor, vitae dignissim tortor efficitur in. In sodales felis ut aliquet facilisis. Vestibulum in dictum risus. Curabitur mollis tincidunt ultricies. Donec et mauris sed turpis ultrices vestibulum et non diam. Morbi vel tellus lorem. Fusce sit amet ultricies nisi. Quisque rhoncus enim ut dolor sagittis consectetur. Mauris non tellus eu dolor posuere tincidunt at nec ex.`,
    `8) Etiam eleifend ex nisi, eu egestas nibh aliquet quis. Nullam nec augue eget sapien dictum semper non in dolor. Ut et orci erat. Cras ut odio augue. Integer at tellus rutrum, condimentum nulla ac, scelerisque magna. Morbi dignissim blandit congue. Suspendisse et erat ut lectus consequat rutrum quis vitae enim. Nullam nisl sem, iaculis vitae tincidunt ac, consectetur sit amet tortor. Mauris interdum, magna id feugiat efficitur, nunc felis gravida ipsum, sed gravida metus nibh sit amet erat. Sed ullamcorper arcu in dui viverra egestas ac id neque. Cras sit amet volutpat lorem, sed bibendum felis. Donec eu suscipit neque. Aenean vitae nunc eget diam placerat posuere. Curabitur vestibulum faucibus feugiat.`

];